#include <LCD5110_Basic.h> // EKRANIMIZIN KÜTÜPHANESİNİ DAHİL EDİYORUZ...
#include "DHT.h" // SICAKLIK SENSÖRÜMÜZÜN KÜTÜPHANESİNİ DAHİL EDİYORUZ...
#define DHTPIN 2 // SICAKLIK SENSÖRÜMÜZÜN BAĞLI OLDUĞU PİNİ BELİRTİYORUZ...
#define DHTTYPE DHT11 // SICAKLIK SENSÖRÜMÜZÜN MODELİNİ BELİRTİYORUZ...
//#define DHTTYPE DHT22
//#define DHTTYPE DHT21

DHT dht(DHTPIN, DHTTYPE); //SENSÖRÜMÜZÜ TANIMLIYORUZ...
LCD5110 myGLCD(8, 9, 10, 11, 12);//EKRANIMIZI TANIMLIYORUZ...

extern uint8_t SmallFont[];
extern uint8_t MediumNumbers[];
extern uint8_t BigNumbers[];
extern uint8_t LOGO[];

void setup()
{
  myGLCD.InitLCD(); //EKRANI BAŞLATIYORUZ...
  dht.begin();//SENSÖRDEN VERİ ALMAK İÇİN İLETİŞİMİ BAŞLATIYORUZ...
  myGLCD.drawBitmap(11, 0, LOGO, 60, 48);//LOGOMUZU ÇİZİYORUZ...
  delay(3500);//3.5 SANİYE BEKLİYORUZ...
}
void loop()
{ 
  myGLCD.clrScr();//EKRANI TEMİZLİYORUZ...
  float h = dht.readHumidity();//NEM DEĞERİNİ ALIYORUZ...
  myGLCD.setFont(SmallFont);//KARAKTER MODUNU SEÇİYORUZ...
  myGLCD.print("%", 25, 24);//DEĞERİN SEMBOLÜNÜ YAZIYORUZ...
  myGLCD.printNumI(h,40,24);//DEĞERİ YAZIYORUZ...
  myGLCD.print("NEM", CENTER, 8);// HANGİ DEĞER OLDUĞUNU BELİRTİYORUZ...
  delay(2000);// 2 SANİYE BEKLİYORUZ...

  myGLCD.clrScr();//EKRANI TEMİZLİYORUZ...
  float t = dht.readTemperature();//SICAKLIK DEĞERİNİ ALIYORUZ...
  myGLCD.setFont(SmallFont);//KARAKTER MODUNU SEÇİYORUZ...
  myGLCD.print("C",45, 24);//DEĞERİN SEMBOLÜNÜ YAZIYORUZ...
  myGLCD.printNumI(t, 30, 24);//DEĞERİ YAZIYORUZ...
  myGLCD.print("SICAKLIK", CENTER, 8);//HANGİ DEĞER OLDUĞUNU BELİRTİYORUZ...
  delay(2000);// 2 SANİYE BEKLİYORUZ...
}
